# Generated by Django 4.1.7 on 2023-03-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskstatus_alter_task_parent_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
