# Generated by Django 4.1.7 on 2023-03-25 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_taskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.taskstatus'),
        ),
    ]
