# Generated by Django 4.1.7 on 2023-03-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_task_status_alter_task_user_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='story_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
