# Generated by Django 4.1.7 on 2023-03-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_task_story_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='story_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
